apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aro-workshop-manager-roles
  namespace: aro-workshop-dev
rules:
- apiGroups: ["", "apiextensions.k8s.io", "apps", "autoscaling", "batch", "events.k8s.io", "networking.k8s.io", "network.openshift.io", "config.openshift.io", "policy", "rbac.authorization.k8s.io", "authorization.openshift.io", "scheduling.k8s.io", "apps.openshift.io", "build.openshift.io", "image.openshift.io", "route.openshift.io"]
  resources: ["configmaps", "endpoints", "events", "limitranges", "persistentvolumeclaims", "secrets", "pods", "pods/exec", "pods/log", "resourcequotas", "serviceaccounts", "namespaces", "services", "customresourcedefinitions", "daemonsets", "deployments", "replicasets", "statefulsets", "horizontalpodautoscalers", "cronjobs", "jobs", "events", "ingresses", "networkpolicies", "egressnetworkpolicies", "poddisruptionbudgets", "rolebindings", "roles", "priorityclasses", "deploymentconfigs", "buildconfigs", "builds", "imagestreams", "imagestreamimports", "routes"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aro-workshop-manager-role-bindings
  namespace: aro-workshop-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aro-workshop-manager-roles
subjects:
- apiGroup: rbac.authorization.k8s.io
  name: architects
  kind: Group